requires 'Amon2';
requires 'JSON';
requires 'Module::Functions';
requires 'Router::Boom';
requires 'Starlet';
requires 'Text::Xslate';
requires "Number::Bytes::Human";
requires "Time::Duration";
requires 'Proclet';
requires 'File::RotateLogs';
requires 'Daemon::Control';
requires 'Amon2::Plugin::Web::Text', 0, git => 'https://github.com/shoichikaji/Amon2-Plugin-Web-Text.git';
